export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_RECIPES_FILTERS = 'GET_RECIPES_FILTERS';
export const GET_ALL_DIETS = 'GET_ALL_DIETS'
