export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_RECIPES_DB = 'GET_RECIPES_DB';
export const GET_RECIPES_API = 'GET_RECIPES_API';
export const GET_RECIPES_AZ = 'GET_RECIPES_AZ';
export const GET_RECIPES_ZA = 'GET_RECIPES_ZA';
