export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
// export const GET_RECIPES_ALPHABETIC = 'GET_RECIPES_ALPHABETIC';
// export const GET_RECIPES_HEALTH = 'GET_RECIPES_HEALTH';
// export const GET_RECIPES_DIETS = 'GET_RECIPES_DIETS';
export const GET_RECIPES_FILTERS = 'GET_RECIPES_FILTERS';
export const GET_ALL_DIETS = 'GET_ALL_DIETS';
export const CREATE_RECIPE = 'CREATE_RECIPE'
